<div class="container">
    <div class="col-10">
        <div id="editor">Add title</div>
        <script>
            ClassicEditor
                .create( document.querySelector( '#editor' ) )
                .then( editor => {
                    console.log( editor );
                } )
                .catch( error => {
                    console.error( error );
                } );
        </script>
    </div>
</div>
