<div class="container">
    <div class="row">
        <div class="col-12 add-form">
            <h1>Éditer la page</h1>
            <?php if(isset($errors) && !empty($errors)): ?>
                <ul>
                    <?php foreach($errors as $error): ?>
                        <li><?php echo $error;?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?= $pageEdit; ?>
        </div>
        <div class="col-12 back-to-list">  <a href="/admin/articles" class="btn btn--infos btn--sm">Revenir à la liste</a></div>
    </div>
</div>

<script>
    ClassicEditor
        .create( document.querySelector( '#content' ) )
        .then( editor => {
            console.log( editor );
        } )
        .catch( error => {
            console.error( error );
        } );
</script>
