<div class="content admin-newsletter--list">
    <div class="col-gutter-12">
        <h1>Personnalisation</h1>
        <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    Taille du titre h1:<br>
                    <input type="range" id="myrange" max="3" step="0.1" min="0.1" value="0.1"/> <span id="displayfontsize"></span> em<br>
                    Changer la couleur : <input type="color" id="colorpick"/>
                    <input type="button" value="Valider" onclick="changecolor()"/><br><br>
                </div>
                <div class="col-6">
                    <p id="txtcolorchange">Title</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    Taille du titre h1:<br>
                    <input type="range" id="myrange" max="3" step="0.1" min="0.1" value="0.1"/> <span id="displayfontsize"></span> em<br>
                    Changer la couleur : <input type="color" id="colorpick"/>
                    <input type="button" value="Valider" onclick="changecolor()"/><br><br>
                </div>
                <div class="col-6">
                    <p id="txtcolorchange">Title</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    Taille du titre h1:<br>
                    <input type="range" id="myrange" max="3" step="0.1" min="0.1" value="0.1"/> <span id="displayfontsize"></span> em<br>
                    Changer la couleur : <input type="color" id="colorpick"/>
                    <input type="button" value="Valider" onclick="changecolor()"/><br><br>
                </div>
                <div class="col-6">
                    <p id="txtcolorchange">Title</p>
                </div>
            </div>
        </div>
    </div>
</div>