<div class="content admin-newsletter--list">
    <div class="col-gutter-12">
        <h1>Personnalisation</h1>
        <form class="container-fluid" action="update">
        <input type="hidden" name="id" value="<?= $customs['id'] ?>">
            <div class="container">
                <div class="shadow shadow--none col-gutter-2">
                    <h6>Taille des en-têtes:</h6>
                    <input type="range" id="h1_range" max="5" step="0.01" min="0.1" value="<?= $customs['h1_size'] ?>" onchange="updateH1Input(this.value);"/>
                    <input type="text" name="h1_size" id="h1_size" value="<?= $customs['h1_size'] ?>"> em</input>
                    <h6>Couleur des en-têtes:</h6>
                    <input type="color" name="h1_color" id="h1_color" value="#<?= $customs['h1_color'] ?>"/>
                    <br><br>
                </div>
                <div class="shadow shadow--none col-gutter-2">
                    <h6>Taille des Titres 1:</h6>
                    <input type="range" id="h2_range" max="5" step="0.01" min="0.1" value="<?= $customs['h2_size'] ?>" onchange="updateH2Input(this.value);"/>
                    <input type="text" name="h2_size" id="h2_size" value="<?= $customs['h2_size'] ?>"> em</input>
                    <h6>Couleur des Titres 1:</h6>
                    <input type="color" name="h2_color" id="h2_color" value="#<?= $customs['h2_color'] ?>"/>
                    <br><br>
                </div>
                <div class="shadow shadow--none col-gutter-2">
                    <h6>Taille des Titres 2:</h6>
                    <input type="range" id="h3_range" max="5" step="0.01" min="0.1" value="<?= $customs['h3_size'] ?>" onchange="updateH3Input(this.value);"/>
                    <input type="text" name="h3_size" id="h3_size" value="<?= $customs['h3_size'] ?>"> em</input>
                    <h6>Couleur des Titres 2:</h6>
                    <input type="color" name="h3_color" id="h3_color" value="#<?= $customs['h3_color'] ?>"/>
                    <br><br>
                </div>
                <div class="shadow shadow--none col-gutter-2">
                    <h6>Taille des Titres 3:</h6>
                    <input type="range" id="h4_range" max="5" step="0.01" min="0.1" value="<?= $customs['h4_size'] ?>" onchange="updateH4Input(this.value);"/>
                    <input type="text" name="h4_size" id="h4_size" value="<?= $customs['h4_size'] ?>"> em</input>
                    <h6>Couleur des Titres 3:</h6>
                    <input type="color" name="h4_color" id="h4_color" value="#<?= $customs['h4_color'] ?>"/>
                    <br><br>
                </div>
                <div class="shadow shadow--none col-gutter-2">
                    <h6>Taille des paragraphes:</h6>
                    <input type="range" id="p_range" max="5" step="0.01" min="0.1" value="<?= $customs['p_size'] ?>" onchange="updatePInput(this.value);"/>
                    <input type="text" name="p_size" id="p_size" value="<?= $customs['p_size'] ?>"> em</input>
                    <h6>Couleur des paragraphes:</h6>
                    <input type="color" name="p_color" id="p_color" value="#<?= $customs['p_color'] ?>"/>
                    <br><br>
                </div>
                <div class="shadow shadow--none col-gutter-2">
                    <h6>Police d'écriture:</h6>
                    <br><br>
                </div>
            </div>

            <br><br>
            <div class="row">
                <input class="btn-success btn" formmethod="post" type="submit" value="Valider la configuration" />
            </div>
        </form>
    </div>
</div>

