<?php
$articleQuery = new App\Query\ArticleQuery();
$articles = $articleQuery->orderByDate();
$verifTable = new \Core\Util\Table();
?>

<div class="site-main--content--articles">
    <?php if ($articles && $verifTable->is_multi($articles)) { ?>
        <?php foreach($articles as $article) { ?>
            <div class="col-gutter-3">
                <a href="/article/<?php echo $article['slug'] ?>" class="data-card">
                    <h5><?php echo $article['title'] ?></h5>
                    <?php if(is_null($article['name'])) { ?>
                        <h6>Pas de catégorie</h6>
                    <?php }else{ ?>
                        <h6><?php echo $article['name'] ?></h6>
                    <?php } ?>
                    <p>
                        <?php if(is_null($article['description'])) { ?>
                            Pas de description
                        <?php }else{ ?>
                            <?php echo $article['description'] ?>
                        <?php } ?>
                        <br><br>
                        <?php echo $article['created_at'] ?>
                    </p>
                    <span class="link-text">
                        Voir l'article
                        <i class="fas fa-arrow-right"></i>
                    </span>
                </a>
            </div>
        <?php } ?>
    <?php } elseif ($articles && !$verifTable->is_multi($articles)) { ?>
            <div class="col-3">
                <a href="/article/<?php echo $articles['slug'] ?>" class="data-card">
                    <h5><?php echo $articles['title'] ?></h5>
                    <?php if(is_null($articles['name'])) { ?>
                        <h6>Pas de catégorie</h6>
                    <?php }else{ ?>
                        <h6><?php echo $articles['name'] ?></h6>
                    <?php } ?>
                    <p>
                        <?php if($articles['description']) { ?>
                            Pas de description
                        <?php }else{ ?>
                            <?php echo $articles['description'] ?>
                        <?php } ?>
                        <br><br>
                        <?php echo $articles['created_at'] ?>
                    </p>
                    <span class="link-text">
                    Voir l'article
                    <i class="fas fa-arrow-right"></i>
                    </span>
                </a>
            </div>
        <?php } else { ?>
            <li>
                <div class="col-3">
                    <h6>Il n'y a pas encore d'article</h6>
                    <a href="/admin/article/add" class="btn btn--sm"><i class="fas fa-plus-circle"></i> Ajouter </a></li>
                </div>
         <?php } ?>
</div>