<?php
use App\Query\ArticleQuery;

$articleQuery = new ArticleQuery();
$articles = $articleQuery->orderByDate();
$articleItem = [];
$articleItem = $articles['title'];

$eventItem = [
    "Event 1" => "<a href=''>",
    "Event 2" => "<a href=''>",
    "Event 3" => "<a href=''>",
    "Event 4" => "<a href=''>",
];

$commentItem = [
    "Comment 1" => "<a href=''>",
    "Comment 2" => "<a href=''>",
    "Comment 3" => "<a href=''>",
    "Comment 4" => "<a href=''>",
];

?>

<aside id="aside" class="site-main--aside">
    <div class="container">
        <hr>
        <h5>Dernières actualités :</h6>
        <hr>
        <h6>Evenements :</h6>
        <ul>
        <?php if($eventItem): ?>
            <?php foreach($eventItem as $name => $link): ?>
                <li>
                    <?php echo $link . $name . "</a>";?>
                </li>
            <?php endforeach;?>
        <?php endif;?>
        </ul>
    </div>
    <div class="container">
        <h6>Articles :</h6>
        <ul>
        <?php if($articleItem): ?>
            <?php foreach($articleItem as $item):?>
                <li>
                    <?php echo $item ;?>
                </li>
            <?php endforeach;?>
        <?php endif;?>
        </ul>
    </div>
    <div class="container">
        <h6>Commentaires :</h6>
        <ul>
        <?php if($commentItem): ?>
            <?php foreach($commentItem as $name => $link): ?>
                <li>
                    <?php echo $link . $name . "</a>";?>
                </li>
            <?php endforeach;?>
        <?php endif;?>
        </ul>
    </div>
    <div class="container">
        <hr>
        <h5>Rechercher sur le site</h5>
        <hr>
        <input type="search" id="site-search" name="q" aria-label="Search through site content">
        <br><br>
        <a href="#" class="btn btn--info btn--sm">Rechercher</a>
    </div>
</aside>