<?php
$request = new \Core\Http\Request();
$path = $request->getPath();
$arr = explode('/', $path);

if ($arr[1] == 'article'){
    $slug=$arr[2];

    $commentQuery = new App\Query\CommentQuery;
    $comments = $commentQuery->getCommentsBySlug($slug);

    $session = new Core\Http\Session();
    $id = $session->getSession('user_id') ?? null;
    $connectedUser = [];
    $testPermission = new \Core\Util\RolePermission();

    $commentIsActive = new \App\Query\ArticleQuery();
    $activeComment = $commentIsActive->getActiveCommentBySlug($slug)['active_comment'];

?>

    <?php if ($activeComment == '1') { ?>
    <section>
        <div class="container--fluid">
            <div class="row">
                <div class="<?php if ($id && $testPermission->has_permission($id, 'crud_self_comment') || $id && $testPermission->has_permission($id, 'crud_comment') ) { ?>
                col-gutter-6  <?php } else{ ?> col-gutter-12 <?php } ?> ">
                    <h2>Commentaires</h2>
                    <?php if(!empty($comments)) {
                        $verifTable = new \Core\Util\Table();
                        if ($verifTable->is_multi($comments)){ ?>
                            <h4><?= count($comments) ?> commentaires</h4>
                            <div id="comment-list-box">
                            <?php foreach($comments as $k=>$v) { ?>
                                <div class="message-box" id="message_<?php echo $comments[$k]["id"];?>">
                                    <div class="message-content">
                                        <h5> <?= $comments[$k]["fullname"] ?> </h5>
                                        <span><?= $comments[$k]["created_at"] ?></span>
                                        <br>
                                        <?php echo $comments[$k]["message"]; ?>
                                        <!--<a href="">Edit</a>
                                        <a href="">Delete</a>-->
                                    </div>
                                </div>
                            <?php } ?>
                        <?php } else{ ?>
                            <h4>1 commentaires</h4>
                            <div id="comment-list-box">
                                <div class="message-box" id="message_<?php echo $comments["id"];?>">
                                    <div class="message-content">
                                        <h5> <?= $comments["fullname"] ?> </h5>
                                        <span><?= $comments["created_at"] ?></span>
                                        <br>
                                        <?php echo $comments["message"]; ?>
                                        <!--<a href="">Edit</a>
                                        <a href="">Delete</a>-->
                                    </div>
                                </div>
                        <?php }
                    } ?>
                    </div>
                </div>
                <?php if ($id && $testPermission->has_permission($id, 'crud_self_comment') || $id && $testPermission->has_permission($id, 'crud_comment') ) { ?>
                <div class="col-gutter-6">
                    <?php $helper = new \Core\Util\Helper() ?>
                    <?php if(($message = $helper->getFlashMessage('flashMessage'))):?>
                        <p><?php echo $message;?></p>
                    <?php endif;?>
                    <form method="post" action="/article/storeComment">
                        <div class="row">
                            <div class="col-12">
                                <h4>Laissez un commentaire</h4>
                                <input type="hidden" name="slug" value="<?= $slug ?>">
                                <label for="message">Message</label> <textarea name="message" id="message" cols="80" rows="10"></textarea>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <input type="submit" value="Poster votre commentaire">
                            </div>
                        </div>
                    </form>
                </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>
<?php } ?>
