<?php
$verifTable = new \Core\Util\Table();
$categoryQuery = new App\Query\CategoryQuery();
$categories = $categoryQuery->orderByDate();
$menuQuery = new App\Query\MenuQuery();
$menuId = $menuQuery->getIdByPosition('footer');
$id = implode($menuId);
$havepageQuery = new App\Query\HavePageQuery();
$pagesId = $havepageQuery->getPagesIdByMenuId($id);
$paramQuery = new App\Query\ParamQuery();
$haveSocial = $paramQuery->getSocials();
$paramQuery = new App\Query\ParamQuery();
$description = $paramQuery->getDescription()['description'];
$paramQuery = new App\Query\ParamQuery();
$siteName = $paramQuery->getSiteName();
?>

<footer class="site-main--footer">
    <div class="container">
        <div class="row">
            <div class="col-6">
                    <h6>À propos</h6>
                    <p>
                        <?= !is_null($description) ? $description : "Un site crée et propulsé par GoSchool" ; ?>
                    </p>
            </div>
            <div class="col-3">
                <h6>Menu</h6>
                <ul class="footer-links">
                    <?php if($pagesId != null) {
                        if ($verifTable->is_multi($pagesId)){
                            $pagesId = $verifTable->multi_to_single($pagesId);
                        }?>
                        <?php foreach($pagesId as $page) {
                            $pageQuery = new App\Query\PageQuery();
                            $pageTitle = $pageQuery->getTitleById($page);
                            $title = implode($pageTitle);
                            $pageQuery = new App\Query\PageQuery();
                            $pageUrl = $pageQuery->getUrlById($page);
                            $url = implode($pageUrl);
                            ?>
                            <li>
                                <a href='<?php echo $url ?>'><?php echo $title ?></a>
                            </li>
                        <?php } ?>
                    <?php }else{ ?>
                        <li>
                            <a href='/'>Welcome</a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <div class="col-3">
                <h6>Catégories</h6>
                <ul class="footer-links">
                    <?php if($categories != null) { ?>
                        <?php for($i = 0; $i < 5;$i++):?>
                            <li>
                                <a href='/<?php echo $categories[$i]['slug']?>'><?php echo $categories[$i]['name']?></a>
                            </li>
                        <?php endfor;?>
                    <?php }else{ ?>
                        <li>
                            <a href=''>Pas de catégorie.</a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-8">
                <p>
                    Copyright &copy; 2021 - Tous droits réservés par <a href="/"><?php echo $siteName['site_name'] ?></a>.
                </p>
            </div>
            <div class="col-4">
                <ul class="social">
                    <?php if($haveSocial['twitter']) : ?>
                        <li><a class="twitter" href="<?php echo $haveSocial['twitter'] ?>"><i class="fab fa-twitter fa-lg"></i></a></li>
                    <?php endif; ?>
                    <?php if($haveSocial['facebook']) : ?>
                        <li><a class="<?php echo $haveSocial['facebook'] ?>" href="#"><i class="fab fa-facebook-f fa-lg"></i></a></li>
                    <?php endif; ?>
                    <?php if($haveSocial['instagram']) : ?>
                        <li><a class="instagram" href="<?php echo $haveSocial['instagram'] ?>"><i class="fab fa-instagram fa-lg"></i></a></li>
                    <?php endif; ?>
                    <?php if($haveSocial['linkedin']) : ?>
                        <li><a class="linkedin" href="<?php echo $haveSocial['linkedin'] ?>"><i class="fab fa-linkedin-in fa-lg"></i></a></li>
                    <?php endif; ?>  
                </ul>
            </div>
        </div>
    </div>
</footer>