<?php
use App\Query\CategoryQuery;
use App\Query\MenuQuery;
use App\Query\HavePageQuery;
use App\Query\PageQuery;

$categoryQuery = new CategoryQuery();
$categories = $categoryQuery->orderByDate();
$menuQuery = new MenuQuery();
$menuId = $menuQuery->getIdByPosition('footer');
$id = implode($menuId);
$havepageQuery = new HavePageQuery();
$pagesId = $havepageQuery->getPagesIdByMenuId($id);

?>

<footer class="site-main--footer">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <h6>About</h6>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed beatae reprehenderit asperiores corporis aperiam quod, eligendi voluptatem, officiis veniam animi, itaque dolorem eveniet laborum possimus modi dolorum blanditiis. Esse, omnis.
                </p>
            </div>
            <div class="col-3">
                <h6>Menu</h6>
                <ul class="footer-links">
                    <?php if($pagesId != null) {?>
                        <?php foreach($pagesId as $page) {
                            $pageQuery = new PageQuery();
                            $pageTitle = $pageQuery->getTitleById($page['page_id']);
                            $title = implode($pageTitle);
                            $pageQuery = new PageQuery();
                            $pageUrl = $pageQuery->getUrlById($page['page_id']);
                            $url = implode($pageUrl);
                            ?>
                            <li>
                                <a href='<?php echo $url ?>'><?php echo $title ?></a>
                            </li>
                        <?php } ?>
                    <?php }else{ ?>
                        <li>
                            <a href='/'>Welcome</a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <div class="col-3">
                <h6>Catégories</h6>
                <ul class="footer-links">
                    <?php if($categories != null) { ?>
                        <?php for($i = 0; $i < 5;$i++):?>
                            <li>
                                <a href=''><?php echo $categories[$i]['name']?></a>
                            </li>
                        <?php endfor;?>
                    <?php }else{ ?>
                        <li>
                            <a href=''>Pas de catégorie.</a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-8">
                <p>
                    Copyright &copy; 2021 - Tous droits réservés par <a href="#">GoSchool</a>.
                </p>
            </div>

            <div class="col-4">
                <ul class="social">
                    <li><a class="facebook" href="#"><i class="fab fa-facebook-f fa-lg"></i></a></li>
                    <li><a class="twitter" href="#"><i class="fab fa-twitter fa-lg"></i></a></li>
                    <li><a class="linkedin" href="#"><i class="fab fa-linkedin-in fa-lg"></i></a></li>   
                </ul>
            </div>
        </div>
    </div>
</footer>