<?php
//@TODO get menu items from database and render

//exemple menu items
$menuItem = [
    "Accueil" => "<a href='/accueil'>",
    "About" => "<a href='/about'>",
    "Products" => "<a href='/products'>",
    "Contact" => "<a href='/contact'>",
];
?>

<header id="header" class="site-main--header">
    <div class="container">
        <nav class="site-main--nav">
            <ul>
            <?php if($menuItem): ?>
                <?php foreach($menuItem as $name => $link): ?>
                    <li>
                        <?php echo $link . $name . "</a>";?>
                    </li>
                <?php endforeach;?>
            <?php endif;?>
            </ul>
        </nav>
    </div>
</header>