<?php

namespace App\Model;
use Core\Database\Model;

class ParamModel extends Model
{
    private $site_name;

    private $url;

    private $visible;

    private $default_role;

    private $default_article_category;

    private $mail_host;

    private $mail_port;

    private $mail_login;

    private $mail_password;

    private $twitter;

    private $facebook;

    private $linkedin;

    private $instagram;

    private $default_home_page;

    private $post_show_count;

    private $description;

    private $theme;

    private $lang;

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @return mixed
     */
    public function getDefaultArticleCategory()
    {
        return $this->default_article_category;
    }

    /**
     * @return mixed
     */
    public function getDefaultHomePage()
    {
        return $this->default_home_page;
    }

    /**
     * @return mixed
     */
    public function getDefaultRole()
    {
        return $this->default_role;
    }

    /**
     * @return mixed
     */
    public function getFacebook()
    {
        return $this->facebook;
    }

    /**
     * @return mixed
     */
    public function getInstagram()
    {
        return $this->instagram;
    }

    /**
     * @return mixed
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * @return mixed
     */
    public function getLinkedin()
    {
        return $this->linkedin;
    }


    /**
     * @return mixed
     */
    public function getMailHost()
    {
        return $this->mail_host;
    }

    /**
     * @return mixed
     */
    public function getMailLogin()
    {
        return $this->mail_login;
    }

    /**
     * @return mixed
     */
    public function getMailPassword()
    {
        return $this->mail_password;
    }

    /**
     * @return mixed
     */
    public function getMailPort()
    {
        return $this->mail_port;
    }

    /**
     * @return mixed
     */
    public function getPostShowCount()
    {
        return $this->post_show_count;
    }

    /**
     * @return mixed
     */
    public function getSiteName()
    {
        return $this->site_name;
    }

    /**
     * @return mixed
     */
    public function getTheme()
    {
        return $this->theme;
    }

    /**
     * @return mixed
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * @return mixed
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @return mixed
     */
    public function getVisible()
    {
        return $this->visible;
    }
    public function errorMessages()
    {
        parent::errorMessages(); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $default_home_page
     */
    public function setDefaultHomePage($default_home_page): void
    {
        $this->default_home_page = $default_home_page;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @param mixed $default_article_category
     */
    public function setDefaultArticleCategory($default_article_category): void
    {
        $this->default_article_category = $default_article_category;
    }

    /**
     * @param mixed $default_role
     */
    public function setDefaultRole($default_role): void
    {
        $this->default_role = $default_role;
    }

    /**
     * @param mixed $facebook
     */
    public function setFacebook($facebook): void
    {
        $this->facebook = $facebook;
    }

    /**
     * @param mixed $instagram
     */
    public function setInstagram($instagram): void
    {
        $this->instagram = $instagram;
    }

    /**
     * @param mixed $lang
     */
    public function setLang($lang): void
    {
        $this->lang = $lang;
    }

    /**
     * @param mixed $linkedin
     */
    public function setLinkedin($linkedin): void
    {
        $this->linkedin = $linkedin;
    }

    /**
     * @param mixed $mail_host
     */
    public function setMailHost($mail_host): void
    {
        $this->mail_host = $mail_host;
    }

    /**
     * @param mixed $mail_login
     */
    public function setMailLogin($mail_login): void
    {
        $this->mail_login = $mail_login;
    }

    /**
     * @param mixed $mail_password
     */
    public function setMailPassword($mail_password): void
    {
        $this->mail_password = $mail_password;
    }

    /**
     * @param mixed $mail_port
     */
    public function setMailPort($mail_port): void
    {
        $this->mail_port = $mail_port;
    }

    /**
     * @param mixed $post_show_count
     */
    public function setPostShowCount($post_show_count): void
    {
        $this->post_show_count = $post_show_count;
    }

    /**
     * @param mixed $site_name
     */
    public function setSiteName($site_name): void
    {
        $this->site_name = $site_name;
    }

    /**
     * @param mixed $theme
     */
    public function setTheme($theme): void
    {
        $this->theme = $theme;
    }

    /**
     * @param mixed $twitter
     */
    public function setTwitter($twitter): void
    {
        $this->twitter = $twitter;
    }

    /**
     * @param mixed $url
     */
    public function setUrl($url): void
    {
        $this->url = $url;
    }

    /**
     * @param mixed $visible
     */
    public function setVisible($visible): void
    {
        $this->visible = $visible;
    }

    public function rules()
    {
        return [
            'site_name' => ['id' => 'name', 'type' => 'string',  'min' => 4,  'max' => 30],
            'mail_host' => ['required' => 'required'],
            'mail_port' => ['required' => 'required', 'type' => 'number'],
            'mail_login' => ['required' => 'required'],
            'mail_pass' => ['required' => 'required'],
            'description' => ['id' => 'description', 'type' => 'string', 'max' => 200],
        ];

    }
}
