<div class="content admin-article--add">
    <h1>Ajouter un nouvelle article</h1>
    <div class="container">
        <div class="container col-6">
            <?php if(isset($errors) && !empty($errors)): ?>
            <ul>
                <?php foreach($errors as $error): ?>
                    <li><?php echo $error;?></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
            <?= $addArticle; ?>
        </div>
    </div>
    <a href="/admin/articles" class="btn btn--infos btn--sm">Revenir à la liste</a>
</div>