<div class="container">
    <div class="content admin-article--add">
        <div class="col-12">
            <h1>Ajouter un nouvel article</h1>
            <?php if(isset($errors) && !empty($errors)): ?>
                <ul>
                    <?php foreach($errors as $error): ?>
                        <li><?php echo $error;?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?= $articleAdd; ?>
            <a href="/admin/articles" class="btn btn--infos btn--sm">Revenir à la liste</a>
        </div>
    </div>
</div>

<script>
    ClassicEditor
        .create( document.querySelector( '#content' ), {
            image: {
                resizeUnit: "%",
                resizeOPtions: [{
                    name: 'resizeImage:original',
                    value: null,
                    label: 'Original size'
                },
                {
                    name: 'resizeImage:50',
                    value: '50',
                    label: 'Medium size'
                },
                {
                    name: 'resizeImage:75',
                    value: '75',
                    label: 'Large size'
                }]
            }
        } )
        .then( editor => {
            console.log( editor );
        } )
        .catch( error => {
            console.error( error );
        } );
</script>