<div class="container">
    <div class="content admin-article--add">
        <div class="col-6">
            <h1>Ajouter un nouvel article</h1>
            <?php if(isset($errors) && !empty($errors)): ?>
                <ul>
                    <?php foreach($errors as $error): ?>
                        <li><?php echo $error;?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?= $articleAdd; ?>
            <a href="/admin/articles" class="btn btn--infos btn--sm">Revenir à la liste</a>
        </div>
    </div>
</div>