<div class="content admin-article--edit">
    <h1>Modifier l'article</h1>
    <div class="container">
        <div class="container col-6">
            <?php if(($message = $helper->getFlashMessage('success'))):?>
            <p><?php echo $message;?></p>
            <?php else:?>
            <p> <?php $errors = $helper->getFlashMessage('errors');?></p>
            <ul>
                <?php foreach($errors as $error): ?>
                    <li><?php echo $error;?></li>
                <?php endforeach; ?>
            </ul>
            <?php endif;?>
            <?= $editArticle; ?>
        </div>
    </div>
    <a href="/admin/articles" class="btn btn--infos btn--sm">Revenir à la liste</a>
</div>