<div class="container">
    <div class="content admin-article--list">
            <div class="col-10">
                <h1>Articles</h1>
            <a href="/admin/article/add" class="btn btn--infos btn--sm"><i class="fas fa-plus-circle"></i> Ajouter un article</a>
                <?php $keys = array_keys($articles);?>

                <?php if(($message = $helper->getFlashMessage('created'))):?>
                    <p><?php echo $message;?></p>
                <?php elseif(($message = $helper->getFlashMessage('edited'))):?>
                    <p> <?php echo $message;?></p>
                <?php elseif(($message = $helper->getFlashMessage('deleted'))):?>
                    <p> <?php echo $message;?></p>
                <?php elseif(($message = $helper->getFlashMessage('failed'))):?>
                    <p> <?php echo $message;?></p>
                <?php endif;?>

                <table id="articles_table" class="display dataTable">
                    <thead>
                            <tr>
                                <th>Id</th>
                                <th>Titre</th>
                                <th>Content</th>
                                <th>Modifier</th>
                                <th>Supprimer</th>
                            </tr>
                    </thead>

                    <tbody>
                    <?php if(!empty($articles)) { ?>
                        <?php for($i = 0; $i < count($articles); $i++) { ?>
                            <tr>
                                <?php foreach($articles[$keys[$i]] as $key => $value) { ?>
                                    <td><?php echo $value ?></td>
                                <?php } ?>
                                <td><a href="article/edit?id=<?php echo $articles[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                                <td><a href="javascript:confirmDelete('article/delete?id=<?php echo $articles[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                            <?php } ?>
                        <?php } ?>
                            </tr>
                    </tbody>

                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Titre</th>
                            <th>Content</th>
                            <th>Modifier</th>
                            <th>Supprimer</th>
                        </tr>
                    </tfoot>
                </table>

                <script>
                    $(document).ready(function() {
                        $('#articles_table').DataTable();
                    } );
                </script>
            </div>
        </div>
    </div>
</div>

