<div class="content admin-comment--list">
    <div class="col-gutter-12">
        <h1>Commentaires de l'article</h1>
        <?php $keys = array_keys($comments);?>
        <?php use Core\Util\Table; ?>
        <?php $verifTable = new Table() ?>

        <?php if(($message = $helper->getFlashMessage('success'))):?>
            <p><?php echo $message;?></p>
        <?php elseif(($message = $helper->getFlashMessage('error'))):?>
            <p> <?php echo $message;?></p>
        <?php endif;?>

        <table id="comments_table" class="display dataTable">
            <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Message</th>
                <th>Publié à</th>
                <th>Par</th>
                <th>Status</th>
                <th>Afficher</th>
                <th>Supprimer</th>
            </tr>
            </thead>

            <tbody>
            <?php if ($comments != null) { ?>
                <?php if($verifTable->is_multi($comments)) { ?>
                    <?php for($i = 0; $i < count($comments); $i++) { ?>
                        <tr>
                            <?php foreach($comments[$keys[$i]] as $key => $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td>
                                <?php if($comments[$i]['status'] == 'Non') { ?>
                                    <a href="comments/publish?id=<?php echo $comments[$i]['id'] ?>" class="btn btn--success btn--sm"><i class="fas fa-share-square"></i></a>
                                <?php } else { ?>
                                    <a href="comments/nopublish?id=<?php echo $comments[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-times"></i></a>
                                <?php } ?>
                            </td>
                            <td><a href="javascript:confirmDelete('comments/delete?id=<?php echo $comments[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                        </tr>
                    <?php }
                }
                else{ ?>
                    <tr>
                        <?php foreach($comments as $value) { ?>
                            <td><?php echo $value ?></td>
                        <?php } ?>
                        <td>
                                <?php if($comments[$i]['status'] == 'Non') { ?>
                                    <a href="comments/publish?id=<?php echo $comments[$i]['id'] ?>" class="btn btn--success btn--sm"><i class="fas fa-share-square"></i></a>
                                <?php } else { ?>
                                    <a href="comments/nopublish?id=<?php echo $comments[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-times"></i></a>
                                <?php } ?>
                            </td>
                        <td><a href="javascript:confirmDelete('comments/delete?id=<?php echo $comments['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                    </tr>
                <?php } ?>
            <?php } ?>
            </tbody>

            <tfoot>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Message</th>
                <th>Publié à</th>
                <th>Par</th>
                <th>Status</th>
                <th>Afficher</th>
                <th>Supprimer</th>
            </tr>
            </tfoot>
        </table>

        <script>
            $(document).ready(function() {
                $('#comments_table').DataTable();
            } );
        </script>
    </div>
</div>

