<div class="content admin-article--list">
    <h1>Liste des articles</h1>
    <div class="container">
        <div class="container col-10">
        <?php $keys = array_keys($articles);?>
        <a href="articles/add" class="btn btn--infos btn--sm"><i class="fas fa-plus-circle"></i> Ajouter</a>
            <table id="articletableid" class="display">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Titre</th>
                            <th>Content</th>
                            <th>Modifier</th>
                            <th>Supprimer</th>
                        </tr>
                    </thead>

                <tbody>
                <tbody>
                <?php if(!empty($articles)) { ?>
                    <?php for($i = 0; $i < count($articles); $i++) { ?>
                        <tr>
                            <?php foreach($articles[$keys[$i]] as $key => $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td><a href="articles/edit?id=<?php echo $articles[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                            <!-- <td><a href="javascript:confirmDelete('article/delete?id=<?php // echo $articles[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td> -->
                            <td><a href="javascript:confirmDelete('articles/delete?id=<?php echo $articles[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                        <?php } ?>
                    <?php } ?>
                    <tr>
                </tbody>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Titre</th>
                        <th>Content</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    <tr>
                </tfoot>
            </table>

            <script>
                $(document).ready(function() {
                    $('#articletableid').DataTable({
                        "serverSide" : true,
                        "searching": true,
                        "paging": true,
                        "pagingType": "full_numbers",
                        "lengthMenu":[
                            [10, 25, 50, -1],
                            [10, 25, 50 ,"All"]
                        ],
                        responsive: true,
                        language: {
                            search: "_INPUT_",
                            searchPlaceholder: "Rechercher",
                        }
                    });
                } );
            </script>
        </div>
    </div>
</div>

