<div class="content admin-article--list">
    <h1>List of articles</h1>
    <div class="container">
        <div class="container__col-12">
        <?php $keys = array_keys($articles);?>
        <a href="article/add" class="btn btn--infos btn--sm">Ajouter</a>
        <a href="article/edit/<?php echo $articles['id'] ?>" class="btn btn--warning btn--sm">Modifier</a>
            <table>
                    <thead>
                    <tr>
                        <?php for($i = 0; $i < 1; $i++) {
                            foreach($articles[$keys[$i]] as $key => $value) { ?>
                        <th><?php echo $key ?></th>
                        <?php } ?>
                        <?php }?>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <?php for($i = 0; $i < count($articles); $i++) { ?>
                            <tr>
                            <?php foreach($articles[$keys[$i]] as $key => $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td><a href="article/edit/<?php echo $articles[$i]['id'] ?>" class="btn btn--warning btn--sm">X</a></td>
                            <td><a href="javascript:confirmDelete('article/delete/<?php echo $articles[$i]['id'] ?>')" class="btn btn--danger btn--sm">X</a></td>
                            <tr>
                            <?php } ?>
                    </tr>
                    </tbody>
                </table>
        </div>
    </div>
</div>

<script>
function confirmDelete(delArticle){
    if (confirm("Voulez vous vraiment supprimer ?")) {
        document.location = delArticle;
    }
}
</script>

