<div class="content admin-article--list">
    <h1>List of articles</h1>
    <div class="container">
        <div class="container__col-12">
            <table>
            <a href="article/add" class="btn btn--success btn--sm">Ajouter un article</a>
                <thead>
                    <tr>
                        <?php foreach($articles as $key => $value):?>
                        <th id="<?php echo $key; ?>" name="<?php echo $key; ?>"><?php echo $key;?></th>
                        <?php endforeach; ?>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach($articles as $key => $value):?>
                        <td><?php echo $value; ?></td>
                        <?php endforeach; ?>
                        <td><a href="article/edit" class="btn btn--warning btn--sm">Modifier</a></td>
                        <td><a href="javascript:confirmDelete('article/delete')" class="btn btn--danger btn--sm">Supprimer</a></td>
                    </tr>
                </tbody>
            </table>
            <a href="article/edit/<?php echo $articles['id'] ?>" class="btn btn--warning btn--sm">Modifier</a>
        </div>
    </div>
</div>

<script>
function confirmDelete(delArticle){
    if (confirm("Voulez vous vraiment supprimer ?")) {
        document.location = delArticle;
    }
}
</script>

