<div class="content admin-article--list">
    <h1>List of articles</h1>
    <div class="container">
        <div class="container__col-12">
            <table>
                <thead>
                    <tr>
                        <?php foreach($articles as $key => $value):?>
                        <th><?php echo $key;?></th>
                        <?php endforeach; ?>
                        <th>Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach($articles as $key => $value):?>
                        <td><?php echo $value; ?></td>
                        <?php endforeach; ?>
                        <td><a href="" class="btn btn--danger btn--sm">x</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

