<h1>Tableau de bord</h1>
<div class="container__fluid">
    <div class="content admin--index">
        <div class="col-12">
            <div class="row">
                <div class="col-3">
                    <table class="shadow shadow--none">
                        <thead>
                            <tr>
                                <th colspan="1">Professeurs</th>
                                <th colspan="1">Eleves</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?php echo $teacherCount; ?></td>
                                <td><?php echo $studentCount; ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-9">
                <img class="img img--center" src="/images/planning.png" alt="planning">
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    <div class="container shadow shadow--none">
                        <h4>Les 5 derniers inscrit.</h4>
                        <?php $cles = array_keys($users);?>
                        <ul>
                            <?php for($y = 0; $y < 5; $y++) { ?>
                                <li>
                                        <?php echo $users[$y]['lastname'] ?> <?php echo $users[$y]['firstname'] ?> <?php echo $users[$y]['roles'] ?><br>
                                        <?php echo $users[$y]['created_at'] ?><br><br>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
                <div class="col-2">
                    <div class="container shadow shadow--none">
                        <h4>Les 5 derniers articles.</h4>
                        <?php $keys = array_keys($articles);?>
                        <ul>
                            <?php for($i = 0; $i < 5; $i++) { ?>
                                <li>
                                        <?php echo $articles[$i]['title'] ?><br>
                                        <?php echo $articles[$i]['created_at'] ?><br><br>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
                <div class="col-8">
                    <div class="container shadow shadow--none">
                        <h4>Les évènements à venir.</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

