/:
  controller: DefaultController
  method: index

/article/show:
  controller: ArticleController
  method: show
  params: id

/admin:
  controller: AdminController
  method: index

/se-connecter:
  controller: AdminController
  method: connexion

