/:
  controller: DefaultController
  method: index
/article/show:
  controller: ArticleController
  method: show
  params: id
/admin:
  controller: AdminController
  method: index
/connexion:
  controller: AdminConnexionController
  method: index