<div class="container">
    <div class="content admin-commentaire--add">
        <div class="col-12">
            <h1>Éditer le commentaire</h1>
            <?php if(isset($errors) && !empty($errors)): ?>
                <ul>
                    <?php foreach($errors as $error): ?>
                        <li><?php echo $error;?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?= $commentEdit; ?>
            <a href="/admin/comments" class="btn btn--infos btn--sm">Revenir à la liste</a>
        </div>
    </div>
</div>