<div class="container">
    <div class="content admin-comment--list">
        <div class="col-10">
            <h1>Commentaires</h1>
            <?php $keys = array_keys($comments);?>
            <?php use Core\Util\Table; ?>
            <?php $verifTable = new Table() ?>

            <?php if(($message = $helper->getFlashMessage('created'))):?>
                <p><?php echo $message;?></p>
            <?php elseif(($message = $helper->getFlashMessage('edited'))):?>
                <p> <?php echo $message;?></p>
            <?php elseif(($message = $helper->getFlashMessage('deleted'))):?>
                <p> <?php echo $message;?></p>
            <?php elseif(($message = $helper->getFlashMessage('failed'))):?>
                <p> <?php echo $message;?></p>
            <?php endif;?>

            <table id="comments_table" class="display dataTable">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Titre</th>
                    <th>Message</th>
                    <th>Status</th>
                    <th>Publié à</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </thead>

                <tbody>
                <?php if ($comments != null) { ?>
                    <?php if($verifTable->is_multi($comments)) { ?>
                        <?php for($i = 0; $i < count($comments); $i++) { ?>
                            <tr>
                                <?php foreach($comments[$keys[$i]] as $key => $value) { ?>
                                    <td><?php echo $value ?></td>
                                <?php } ?>
                                <td><a href="comment/edit?id=<?php echo $comments[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                                <td><a href="javascript:confirmDelete('comment/delete?id=<?php echo $comments[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                            </tr>
                        <?php }
                    }
                    else{ ?>
                        <tr>
                            <?php foreach($comments as $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td><a href="comment/edit?id=<?php echo $comments['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                            <td><a href="javascript:confirmDelete('comment/delete?id=<?php echo $comments['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>

                <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Titre</th>
                    <th>Message</th>
                    <th>Status</th>
                    <th>Publié à</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </tfoot>
            </table>

            <script>
                $(document).ready(function() {
                    $('#comments_table').DataTable();
                } );
            </script>
        </div>
    </div>
</div>
</div>

