<div class="container">
<div>
    <h1>Ajouter un utilisateur</h1>

    <?php if(isset($errors) && !empty($errors)): ?>
        <ul>
            <?php foreach($errors as $error): ?>
                <li><?php echo $error;?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <?= $userAdd; ?>
</div>
    <a href="/admin/users" class="btn btn--infos btn--sm">Revenir à la liste des utilisateurs</a>
</div>
