<div class="container">
    <div class="container__col-12">
    <?php if(isset($errors) && !empty($errors)): ?>
        <ul>
            <?php foreach($errors as $error): ?>
                <li><?php echo $error;?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if(($message = $helper->getFlashMessage('success'))):?>
        <p><?php echo $message;?></p>
    <?php endif;?>
    <div>
        <h1>Editer l'utilisateur</h1>
        <?= $editUser; ?>
    </div>
        <a href="/admin/users" class="btn btn--infos btn--sm">Revenir à la liste</a>
    </div>
</div>
