<div class="container">
    <div class="container__col-12">
    <div>
        <h1>Editer l'utilisateur</h1>

        <?php if(isset($errors) && !empty($errors)): ?>
            <ul>
                <?php foreach($errors as $error): ?>
                    <li><?php echo $error;?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?= $editUser; ?>
    </div>
        <a href="/admin/users" class="btn btn--infos btn--sm">Revenir à la liste</a>
    </div>
</div>
