<body>
	<div class="container">
		<div class="row">
			<div class="col-6">
				<div class="logoContainer">
					<img src="../../../../public/librairies/images/connexion.jpg" alt="go school logo">
					<p>Bienvenue à l’école de la réussite</p>
				</div>
			</div>
			<div class="col-6">
				<div class="row">
					<div class="col-12">
						<div class="content formContainer--form white">
                        <?php echo $userLogin; ?>
						</div>
					</div>
					<div class="col-12">
						<div class="formContainer--contact white">
                            <button class="button button--contact"><a href="/admin/lostpassword">Mot de passe oublié ?</a></button>
							<p>Vous n'avez pas encore de compte ?</p>
							<button type="submit" class="button button--contact"><a href="/admin/register">S'inscrire </a></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>