<div>
    <div class="container">
        <h1>Utilisateurs</h1>
        <a class="btn" href="/admin/users/add">Ajouter un utilisateur</a>
        <div class="container">
            <div class="container__col-12">
                <?php $keys = array_keys($users);?>

                <table class="display">
                    <thead>
                    <tr>
                        <?php for($i = 0; $i < 1; $i++) {
                            foreach($users[$keys[$i]] as $key => $value) { ?>
                        <th><?php echo $key ?></th>
                        <?php } ?>
                        <?php }?>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <?php for($i = 0; $i < count($users); $i++) { ?>
                            <tr>
                            <?php foreach($users[$keys[$i]] as $key => $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td><a href="users/edit?id=<?php echo $users[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                            <td><a href="javascript:confirmDelete('users/delete?id=<?php echo $users[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                            <tr>
                            <?php } ?>
                    </tr>
                    </tbody>

                    <tfoot>
                    <tr>
                        <?php for($i = 0; $i < 1; $i++) {
                            foreach($users[$keys[$i]] as $key => $value) { ?>
                                <th><?php echo $key ?></th>
                            <?php } ?>
                        <?php }?>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>