<div class="container">
    <div content admin-user--list>
        <h1>Utilisateurs</h1>
        <a class="btn" href="/admin/users/add" class="btn btn--infos btn--sm"><i class="fas fa-plus-circle"></i>Ajouter un utilisateur</a>
        <div class="col-12">
            <?php $keys = array_keys($users);?>

            <table id="users_table" class="display dataTable">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </thead>
                <tbody>
                <tbody>
                <?php if(!empty($users)) { ?>
                    <?php for($i = 0; $i < count($users); $i++) { ?>
                <tr>
                        <?php foreach($users[$keys[$i]] as $key => $value) { ?>
                            <td><?php echo $value ?></td>
                        <?php } ?>
                    <td><a href="users/edit?id=<?php echo $users[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                    <td><a href="javascript:confirmDelete('users/delete?id=<?php echo $users[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                    <?php } ?>
                <?php } ?>
                </tr>
                </tbody>
                </tbody>

                <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </tfoot>
            </table>

            <script>
                $(document).ready( function () {
                    $('#users_table').DataTable({
                        "processing" : true,
                        "serverSide" : true
                        //"ajax": ""
                    });
                });
            </script>

        </div>
    </div>
    </div>
</div>