<div class="container">
    <div class="content admin-media--add">
        <div class="col-6">
            <h1>Ajouter une image</h1>
            <form method="POST" enctype="multipart/form-data">
            <h3>Inserer l'image</h3>
            <input type="file" name="image" id="image" />
            <input type="submit" class="btn btn--success btn--md" value="envoyer" />
            <input type="hidden" value="b" name="env"/>
            </form>
            <a href="/admin/medias" class="btn btn--infos btn--sm">Revenir à la liste</a>
        </div>
    </div>
</div>