<div class="content admin-event--list">
    <div class="col-gutter-12">
        <h1>Événements</h1>
        <a class="btn" href="/admin/event/add" class="btn btn--infos btn--sm"><i class="fas fa-plus-circle"></i>Ajouter un événement</a>
        <?php $keys = array_keys($events);?>
        <?php use Core\Util\Table; ?>
        <?php $verifTable = new Table();?>

        <?php if(($message = $helper->getFlashMessage('flashMessage'))):?>
            <p><?php echo $message;?></p>
        <?php endif;?>

        <table id="events_table" class="display dataTable">
            <thead>
            <tr>
                <th>Numéro</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Catégorie</th>
                <th>Statut</th>
                <th>Créateur</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>Crée le</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            </thead>

            <tbody>
            <?php if ($events != null) { ?>
                <?php if($verifTable->is_multi($events)) { ?>
                    <?php for($i = 0; $i < count($events); $i++) { ?>
                        <tr>
                            <?php foreach($events[$keys[$i]] as $key => $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td><a href="/admin/event/edit?id=<?php echo $events[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                            <td><a href="javascript:confirmDelete('/admin/event/delete/<?php echo $events[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                        </tr>
                    <?php }
                }
                else{ ?>
                    <tr>
                        <?php foreach($events as $value) { ?>
                            <td><?php echo $value ?></td>
                        <?php } ?>
                        <td><a href="/admin/event/edit?id=<?php echo $events['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                        <td><a href="javascript:confirmDelete('/admin/event/delete/<?php echo $events['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                    </tr>
                <?php } ?>
            <?php } ?>
            </tbody>

            <tfoot>
            <tr>
                <th>Numéro</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Catégorie</th>
                <th>Statut</th>
                <th>Créateur</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>Crée le</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            </tfoot>
        </table>

        <script>
            $(document).ready( function () {
                $('#events_table').DataTable();
            });
        </script>

    </div>