<div class="content admin-medias">
    <h1>Liste des medias</h1>
    <div class="container">
        <div class="container__col-12">
            <img src="<?= $listMedias; ?>" alt="go school logo">
            <?php $keys = array_keys($listMedias);?>
                <a href="article/add" class="btn btn--infos btn--sm"><i class="fas fa-plus-circle"></i> Ajouter</a>
            <table id="mediatableid" class="display">
                <thead>
                    <tr>
                        <?php for($i = 0; $i < 1; $i++) {
                            foreach($listMedias[$keys[$i]] as $key => $value) { ?>
                        <th><?php echo $key ?></th>
                        <?php } ?>
                        <?php }?>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                    <?php for($i = 0; $i < count($listMedias); $i++) { ?>
                        <tr>
                            <?php foreach($listMedias[$keys[$i]] as $key => $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td><a href="article/edit?id=<?php echo $listMedias[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                            <td><a href="javascript:confirmDelete('article/delete?id=<?php echo $listMedias[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                        <tr>
                        <?php } ?>
                </tbody>
                <tfoot>
                    <tr>
                        <?php for($i = 0; $i < 1; $i++) {
                            foreach($listMedias[$keys[$i]] as $key => $value) { ?>
                        <th><?php echo $key ?></th>
                        <?php } ?>
                        <?php }?>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    <tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>