<h1>Paramètres</h1>
<div class="content admin-parameters">
            <div class="container row">
                <div class="col-4">
                <h2>Général</h2>
                <?= $paramEditForm; ?>
                </div>
                <div class="col-2">
                </div>
                <div class="col-6">
                <h2>Mises à jour de GoSchool</h2>
                    <p>
                        Dernière vérification le JJ/MM/AAAA à HH:MM. <a href="#" class="btn btn--primary btn--sm">Vérifier</a>
                    </p>
                    <p>
                        <B>Vous avez la dernière version 0.2 de GoSchool. Les prochaines mises à jours seront appliqués automatiquement.</B>
                    </p>
                    <p>
                        SI vous voulez réinstaller la version 0.1 ultérieure, vous pouvez le faire ici : <a href="#" class="btn btn--primary btn--sm">Réinstaller</a>
                    </p>
                    <p>
                        <B>Nouvelles fonctionnalités de la version 0.2 :</B>
                        <li>Ajouter des vidéos</li>
                        <li>Thème sombre</li>
                        <li>Sauvegarde automatique</li>
                        <li>Nouveau design</li>
                    </p>
                </div>
            </div>
</div>