<div class="container">
    <div class="row">
        <div class="col-12 add-form">
            <h1>Éditer la catégorie</h1>
            <?php if(isset($errors) && !empty($errors)): ?>
                <ul>
                    <?php foreach($errors as $error): ?>
                        <li><?php echo $error;?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?= $categoryEdit; ?>
        </div>
        <div class="col-12 back-to-list">  <a href="/admin/categories" class="btn btn--infos btn--sm">Revenir à la liste</a></div>
    </div>
</div>