<div class="container">
    <div class="content admin-categorie--list">
        <div class="col-10">
            <h1>Catégories</h1>
            <a href="/admin/categorie/add" class="btn btn--infos btn--sm"><i class="fas fa-plus-circle"></i> Ajouter une categorie</a>
            <?php $keys = array_keys($categories);?>
            <?php use Core\Util\Table; ?>
            <?php $verifTable = new Table() ?>

            <?php if(($message = $helper->getFlashMessage('created'))):?>
                <p><?php echo $message;?></p>
            <?php elseif(($message = $helper->getFlashMessage('edited'))):?>
                <p> <?php echo $message;?></p>
            <?php elseif(($message = $helper->getFlashMessage('deleted'))):?>
                <p> <?php echo $message;?></p>
            <?php elseif(($message = $helper->getFlashMessage('failed'))):?>
                <p> <?php echo $message;?></p>
            <?php endif;?>

            <table id="categories_table" class="display dataTable">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Slug</th>
                    <th>Description</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </thead>

                <tbody>
                <?php if ($categories != null) { ?>
                    <?php if($verifTable->is_multi($categories)) { ?>
                        <?php for($i = 0; $i < count($categories); $i++) { ?>
                            <tr>
                                <?php foreach($categories[$keys[$i]] as $key => $value) { ?>
                                    <td><?php echo $value ?></td>
                                <?php } ?>
                                <td><a href="categorie/edit?id=<?php echo $categories[$i]['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                                <td><a href="javascript:confirmDelete('categorie/delete?id=<?php echo $categories[$i]['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                            </tr>
                        <?php }
                    }
                    else{ ?>
                        <tr>
                            <?php foreach($categories as $value) { ?>
                                <td><?php echo $value ?></td>
                            <?php } ?>
                            <td><a href="categorie/edit?id=<?php echo $categories['id'] ?>" class="btn btn--warning btn--sm"><i class="fas fa-edit"></i></a></td>
                            <td><a href="javascript:confirmDelete('categorie/delete?id=<?php echo $categories['id'] ?>')" class="btn btn--danger btn--sm"><i class="fas fa-trash-alt"></i></a></td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>

                <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Slug</th>
                    <th>Description</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </tfoot>
            </table>

            <script>
                $(document).ready(function() {
                    $('#categories_table').DataTable();
                } );
            </script>
        </div>
    </div>
</div>
</div>

