<?php include "/layouts/header.phtml"?>

    <div class="content email-userRegister">
        <p>Vous venez de vous inscrire sur GoSchool. Veuillez cliquer sur le lien ci-dessous pour vérifier votre compte et commencer à profiter de nos services.</p>
        <p>Si l'inscription ne vient pas de vous, veuillez ignorer cet email.</p>
        <p>Voici le lien de validation de votre compte :  </p>
        <a href="%url%">%url%</a>
    </div>
<?php include "/layouts/footer.phtml"?>