<div class="content admin-login">
    <h1>Connexion</h1>
            <div class="content formContainer--form white">
                <?php echo $userLogin; ?>
            </div>
        <div class="content formContainer--contact white">
            <a href="/admin/lostpassword">Mot de passe oublié ?</a><br>
            <a href="/admin/register">Vous n'avez pas encore de compte ? Inscrivez vous ! </a></button>
        </div>
</div>