<body>
    <div class="content admin--login">
        <h1>Réinitialisation du mot de passe</h1>
        <?php if(isset($errors) && !empty($errors)): ?>
            <ul>
                <?php foreach($errors as $error): ?>
                    <li><?php echo $error;?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php echo $userResetPassword; ?>
    </div>
</body>
</html>