<!DOCTYPE html>
<head>
<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Goschool - Installation</title>
    <link rel="stylesheet" type="text/css" href="/librairies/dist/main.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="/librairies/dist/main.js"></script>
</head>
<body class="installation">   
<div class="container">
        <h1>Assistant d'installation</h1>

        <div class="container install">
            <form id="regForm" action="/installation/store" method="post">
                <div class="container database tab">
                     <h3>Information de la base des données</h3>
                    <div class="row">
                        <div class="col-12">
                            <div class="container">
                           
                            <div class="input-group"
                                <label>Nom de la base</label>
                                <input type="text" name="db_name" oninput="this.className = ''"/>
                            </div>
                            <div class="input-group"
                                <label>Utilisateur</label>
                                <input type="text" name="db_user" oninput="this.className = ''"/>
                            </div>
                            <div class="input-group"
                                <label>Mot de passe</label>
                                <input type="password" name="db_password" oninput="this.className = ''"/>
                            </div>
                            <div class="input-group"
                                <label>Host</label>
                                <input type="text" name="db_host" oninput="this.className = ''"/>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container database tab">
                     <h3>Utilisateur administrateur</h3>
                    <div class="row">
                        <div class="col-12">
                            <div class="container">
                           
                            <div class="input-group"
                                <label>Prénom</label>
                                <input type="text" name="firstname" oninput="this.className = ''"/>
                            </div>
                            <div class="input-group"
                                <label>Nom</label>
                                <input type="text" name="lastname" oninput="this.className = ''"/>
                            </div>
                            <div class="input-group"
                                <label>Email</label>
                                <input type="email" name="email" oninput="this.className = ''"/>
                            </div>
                            <div class="input-group"
                                <label>Mot de passe</label>
                                <input type="password" name="password" oninput="this.className = ''"/>
                            </div>
                            <div class="input-group"
                                <label>Mot de passe</label>
                                <input type="password" name="confirmPassword" oninput="this.className = ''"/>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>

            <div style="overflow:auto;">
                <div style="float:right;">
                    <button type="button" id="prevBtn" onclick="nextPrev(-1)">Précédent</button>
                    <button type="button" id="nextBtn" onclick="nextPrev(1)">Suivant</button>
                </div>
            </div>

            <div style="text-align:center;margin-top:40px;">
                <span class="step"></span>
                <span class="step"></span>
            </div>                    
            </form>

            <div class="container">
                <?php if($errors = $helper->getFlashMessage('errors')):?>
                    <ul>
                    <?php foreach($errors as $error):?>
                        <li><?= $error;?></li>
                    <?php endforeach;?>
                    </ul>
                <?php endif;?>
            </div>
        </div>
    </div>
</body>
</html>