<div class="content admin-newsletter--list">
    <div class="col-gutter-12">
        <h1>Newsletter</h1>

        <div class="container--fluid">
            <div class="row">
                <div class="col-lg-gutter-12">
                    <h4>Restez à l'écoute. Nous lançons bientôt cette nouvelle feature newsletter dans la version 2.0 de GoSchool. Nous travaillons dur et nous sommes presque prêts à la lancer !</h4>
                </div>
            </div>
        </div>

        <?php if(($message = $helper->getFlashMessage('flashMessage'))):?>
            <p><?php echo $message;?></p>
        <?php endif;?>
    </div>
</div>