<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin</title>
    <link rel="stylesheet" type="text/css" href="/librairies/dist/main.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    <script src="/librairies/dist/main.js"></script>
</head>
<body>
    <div class="admin-sidebar">
        <nav class="admin-main--menu">
            <div class="logo">
                <a href="#"><img src="/images/logo.png" alt=""></a>
            </div>
            <div class="dashboard-home">
                <a href="#"><i class="fas fa-tachometer-alt"></i>Tableau de bord</a>
            </div>
            <div class="admin-menu-links">
                <ul>
                <li><a href="#">Pages</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">Catégories</a></li>
                <li><a href="#">Planning</a></li>
                <li><a href="#">Newsletters</a></li>
                </ul>
            </div>
            <div class="parameters">
            <a href="#"><i class="fad fa-badge-dollar"></i>Paramètres</a>
            </div>
        </nav>

    </div>
    <div class="admin-topbar">
        <div class="user-controls">
            <div class="identity">
                <div class="img">

                </div>
                <p class="fullname">Christian Mohindo</p>
            </div>
            <div class="user-actions">
                <ul>
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Déconnexion</a></li>
                </ul>
            </div>  
        </div>
    </div>
    <div class="admin-main--content">
        {{content}}
    </div>

    <footer class="admin-main--footer"><h2>Footer</h2></footer>
</body>
</html>