<?php
    use App\Query\UserQuery;
    use Core\Http\Session;
    use Core\Util\SessionHelper;

    $sessionHelper = new SessionHelper();
    $session = new Session();
    $sessionHelper->redirectToLoginIfNotConnected();

    $user = new UserQuery();
    $memberResult = $user->getUserById($session->getSession('id'));
    $firstname = $memberResult['firstname'];
    $lastname = $memberResult['lastname'];
?>


<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>goSchool - Admin</title>
    <link rel="stylesheet" type="text/css" href="/librairies/dist/main.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="/librairies/dist/main.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/librairies/webpack/node_modules/chart.js/dist/chart.js"></script>
    <link href='/librairies/webpack/node_modules/fullcalendar/main.css' rel='stylesheet' />
    <script src='/librairies/webpack/node_modules/fullcalendar/main.js'></script>
</head>
<body>
    <div class="container--fluid">
        <div class="row">
            <div class="col-12">
                <div class="admin-topbar">
                    <div class="user-controls">
                        <div class="identity">
                            <ul>
                                <?php
                                if (isset($firstname)&& isset($lastname)){ ?>
                                <li><a href="/admin/user/profil"><i class="fas fa-user"><?= $firstname . $lastname ?></i></a></li>
                                <?php }  ?></a></li>
                                | <li><a href="/admin/auth/logout">Déconnexion</a></li>
                            </ul>
                        </div>
                        <div class="user-actions">
                            <ul>
                                <li><a href="/admin/article/add"><i class="fas fa-plus"></i>Ajouter</a></li>
                                <li><a href="/">Voir le site</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-4">
                <div class="admin-sidebar">
                    <nav class="admin-main--menu">
                        <div class="logo">
                            <a href="/admin/dashboard/index"><img src="/images/logo.png" alt=""></a>
                        </div>
                        <div class="admin-menu-links">
                            <ul>
                                <li><a href="/admin/dashboard/index"><i class="fas fa-tachometer-alt"></i>Tableau de bord</a></li>
                                <li><a href="/admin/article/list"><i class="fas fa-pen"></i>  Articles</a></li>
                                <li><a href="/admin/category/list"><i class="fas fa-book-open"></i>  Catégories</a></li>
                                <li><a href="/admin/page/list"><i class="fas fa-copy"></i>  Pages</a></li>
                                <li><a href="/admin/media/list"><i class="fas fa-photo-video"></i>  Médias</a></li>
                                <li><a href="#"><i class="fas fa-brush"></i>  Apparence</a></li>
                                <li><a href="/admin/user/list"><i class="fas fa-user"></i>  Utilisateurs</a></li>
                                <li><a href="/admin/comment/list"><i class="fas fa-comment"></i>  Commentaires</a></li>
                                <li><a href="#"><i class="far fa-calendar-alt"></i>  Planning</a></li>
                                <li><a href="#"><i class="far fa-newspaper"></i>  Newsletters</a></li>
                            </ul>
                        </div>
                        <div class="admin-menu-links parameters">
                            <ul>
                                <li><a href="/admin/param/index"><i class="fas fa-cog"></i> Paramètres</a></li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>

            <div class="col-8">
                <div class="admin-main--content">
                        {{content}}
                </div>
            </div>
        </div>

    </div>
</body>
<script>
function confirmDelete(delArticle){
    if (confirm("Voulez vous vraiment supprimer ?")) {
        document.location = delArticle;
    }
}
</script>
</html>