<!DOCTYPE html>
<html lang="fr">
<head>
    <base href="/public/" />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Ressource not found">
    <title>Error 404</title>
    <link rel="stylesheet" type="text/css" href="/librairies/dist/main.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="/librairies/dist/main.js"></script>
</head>
<body class="error-body">
<div class="container--fluid">
     {{content}}
</div>

</body>
</html>