<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Site</title>
        <link rel="stylesheet" type="text/css" href="/librairies/dist/main.css">
        <link rel="stylesheet" type="text/css" href="/librairies/fontawesome/css/fontawesome.min.css">
        <script src="/librairies/dist/main.js"></script>
    </head>
    <body>
        <header class="site-main--header">
            <div class="container">
                <nav class="site-main--nav">
                    <ul>
                        <li><a class="active" href="#home">Accueil</a></li>
                        <li><a href="#article1">Article1</a></li>
                        <li><a href="#article2">Article2</a></li>
                        <li><a href="#article3">Article3</a></li>
                        <li><a href="#contact">Contact</a></li>
                        <li><a href="#foot">Footer</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div class="site-main--content">
            {{content}}
        </div>

        <footer class="site-main--footer">
            <h2>Footer</h2>
        </footer>
    </body>
</html>