<?php
require_once dirname(dirname(dirname(__DIR__))) . DIRECTORY_SEPARATOR ."Core" . DIRECTORY_SEPARATOR . "bootstrap.php";

$layout = new Core\Routing\Layout();

?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <base href="/public/" />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site</title>
    <link rel="stylesheet" type="text/css" href="/librairies/dist/main.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="/librairies/dist/main.js"></script>
</head>
<body>
<?php echo $layout->getMenu();?>

<?php echo $layout->getAside();?>
<div class="site-main--content">
    <?php echo $layout->getContent();?>
</div>

<?php echo $layout->getFooter();?>
</body>
</html>